
version: '2'
services:
  jenkins:
    image: joetestjenkins:latest
    container_name: jenkins
    user: jenkins
    environment:
      JENKINS_HOST_HOME: "/data/jenkins"
    ports:
      - "8083:8083"
    volumes:
      - /data/jenkins:/var/jenkins_home
